version: "3.4"

services:
  node-course:
    build: .
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - ./:/home/node/app
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
